insert into PRODUCT (title, cost) values ('Cloves - Whole', 321.7);
insert into PRODUCT (title, cost) values ('Apple - Northern Spy', 3483.35);
insert into PRODUCT (title, cost) values ('Bacardi Breezer - Strawberry', 383.81);
insert into PRODUCT (title, cost) values ('Arizona - Plum Green Tea', 2334.05);
insert into PRODUCT (title, cost) values ('Bar Special K', 671.45);
insert into PRODUCT (title, cost) values ('Appetizer - Smoked Salmon / Dill', 3191.63);
insert into PRODUCT (title, cost) values ('Magnotta - Bel Paese White', 698.89);
insert into PRODUCT (title, cost) values ('Shrimp - 16/20, Iqf, Shell On', 778.2);
insert into PRODUCT (title, cost) values ('Hold Up Tool Storage Rack', 3637.77);
insert into PRODUCT (title, cost) values ('Wine - Cotes Du Rhone Parallele', 1469.61);
insert into PRODUCT (title, cost) values ('Cheese - Shred Cheddar / Mozza', 1155.33);
insert into PRODUCT (title, cost) values ('Oranges - Navel, 72', 2979.93);
insert into PRODUCT (title, cost) values ('Wine - Gato Negro Cabernet', 2979.93);
insert into PRODUCT (title, cost) values ('Cheese - Feta', 1913.18);
insert into PRODUCT (title, cost) values ('Oil - Olive', 3363.87);
insert into PRODUCT (title, cost) values ('Chicken Giblets', 4848.1);
insert into PRODUCT (title, cost) values ('Honey - Lavender', 484.47);
insert into PRODUCT (title, cost) values ('Tea - Mint', 1492.7);
insert into PRODUCT (title, cost) values ('Beef - Bones, Cut - Up', 3401.66);
insert into PRODUCT (title, cost) values ('Wine - Chateau Timberlay', 3052.49);
